name: Deploy Web to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js (just for fun, optional)
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Build step (CI simulation)
        run: |
          echo "✅ Code validated"
          ls -l

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: https://github.com/asaufi.github.io/ci-cd-test-web
